apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
  namespace: shopfront

spec:
  replicas: 1

  selector:
    matchLabels:
      app: shopfront

  template:
    metadata:
      labels:
        app: shopfront

    spec:
      containers:
      - name: shopfront

        image: 510473517908.dkr.ecr.ap-south-1.amazonaws.com/shopfront-react-app@sha256:1601c51d2be352ef37786567f40620b7c01b771846ed0c104a6c8fbc0783e072

        imagePullPolicy: Always

        ports:
        - containerPort: 80
