apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
  namespace: shopfront

spec:
  replicas: 1

  selector:
    matchLabels:
      app: shopfront

  template:
    metadata:
      labels:
        app: shopfront

    spec:
      containers:
      - name: shopfront

        image: 510473517908.dkr.ecr.ap-south-1.amazonaws.com/shopfront-react-app@sha256:50cff33092e4b220adcbfa363204a59adb7c78adb787c47e6dd6afd0e44f647f

        imagePullPolicy: Always

        ports:
        - containerPort: 80
