apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: 510473517908.dkr.ecr.ap-south-1.amazonaws.com/shopfront-react-app
    newTag: placeholder
