apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- digest: sha256:f78bd223c7881c860b596e52047248a8d9fd8937668b01ba7c1f3b3c71cc2026
  name: 510473517908.dkr.ecr.ap-south-1.amazonaws.com/shopfront-react-app
